### ISSUE TITLE
How to Benchmark TF32 Performance on MI300X GPUs

### ISSUE THREAD

**Issue by Kyogre-Primal** [ROCm/rocWMMA#458]
Hello,

I am currently using an AMD MI300X GPU. According to the datasheet, TF32 precision is supported and should offer up to a 4x speedup over standard FP32 computations. However, when I run the following test code, I observe that the computation speed is the same as with FP32, but the numerical errors are significantly larger.

```hip
// tf32 version

constexpr uint8_t M_TILE = 32u;
constexpr uint8_t N_TILE = 32u;
constexpr uint8_t K_TILE = 4u;

constexpr uint8_t WAVEFRONT_PER_BLOCK = 4u;

typedef float v2f    __attribute__((ext_vector_type(2)));
typedef float v16f   __attribute__((ext_vector_type(16)));

__global__ void convolution_3d_forward_kernel(
        float * storer,
        const float * in_tensor,
        const float * filter_tensor,

        const uint64_t M,
        const uint32_t N,
        const uint32_t K,

        const uint16_t batch_size,
        const uint16_t in_channels,
        const uint16_t out_channels,

        const uint16_t in_depth,
        const uint16_t in_height,
        const uint16_t in_width,

        const uint16_t filter_depth,
        const uint16_t filter_height,
        const uint16_t filter_width,

        const uint16_t padding_depth,
        const uint16_t padding_height,
        const uint16_t padding_width,

        const uint16_t out_depth,
        const uint16_t out_height,
        const uint16_t out_width,

        const uint32_t in_hw,
        const uint64_t in_dhw,
        const uint64_t in_cdhw,

        const uint32_t filter_hw,
        const uint64_t filter_dhw,
        const uint64_t filter_cdhw,

        const uint32_t out_hw,
        const uint64_t out_dhw,
        const uint64_t out_cdhw
){
    const uint8_t lane = __lane_id();

    const uint8_t n = lane & 31u;
    const uint8_t k = lane >> 5u;

    v2f vec_a = {.0f};
    v2f vec_b = {.0f};
    v16f vec_c = {.0f};

    uint32_t __row = ((blockIdx.x << 2) + (threadIdx.x >> 6)) * M_TILE;
    uint32_t __col = blockIdx.y * N_TILE;

    for (uint32_t i = 0; i < K; i += K_TILE){
        uint64_t slice_row = __row + n;

        #pragma unroll 2
        for (uint8_t j = 0; j < 2; j ++){
            uint64_t slice_col = i + (k << 1) + j;

            uint32_t b = slice_row / out_dhw;
            uint32_t ic = slice_col / filter_dhw;
            int32_t id = slice_row / out_hw % out_depth + slice_col / filter_hw % filter_depth - padding_depth;
            int32_t ih = slice_row / out_width % out_height + slice_col / filter_width % filter_height - padding_height;
            int32_t iw = slice_row % out_width + slice_col % filter_width - padding_width;

            bool valid = (b < batch_size) && (ic < in_channels) &&
                         (id >= 0) && (id < in_depth) &&
                         (ih >= 0) && (ih < in_height) &&
                         (iw >= 0) && (iw < in_width);

            vec_a[j] = valid ? in_tensor[(((b * in_channels + ic) * in_depth + id) * in_height + ih) * in_width + iw] : 0.0f;
            vec_b[j] = filter_tensor[__col + n + (i + (k << 1) + j) * N];
        }

        vec_c = __builtin_amdgcn_mfma_f32_32x32x4_xf32(vec_a, vec_b, vec_c, 0, 0, 0);
    }

    #pragma unroll 16
    for(uint8_t s = 0; s < 16; ++s){
        // printf("%d, %d, %d, %f\n", n, k, s, vec_c[s]);
        storer[n + __col + ((s << 1) + (k << 2) - (s & 3) + __row) * N] = vec_c[s];
    }
}
```

```hip
// fp32 version

constexpr uint8_t M_TILE = 32u;
constexpr uint8_t N_TILE = 32u;
constexpr uint8_t K_TILE = 2u;

constexpr uint8_t WAVEFRONT_PER_BLOCK = 4u;

typedef float v2f    __attribute__((ext_vector_type(2)));
typedef float v16f   __attribute__((ext_vector_type(16)));

__global__ void convolution_3d_forward_kernel(
        float * storer,
        const float * in_tensor,
        const float * filter_tensor,

        const uint64_t M,
        const uint32_t N,
        const uint32_t K,

        const uint16_t batch_size,
        const uint16_t in_channels,
        const uint16_t out_channels,

        const uint16_t in_depth,
        const uint16_t in_height,
        const uint16_t in_width,

        const uint16_t filter_depth,
        const uint16_t filter_height,
        const uint16_t filter_width,

        const uint16_t padding_depth,
        const uint16_t padding_height,
        const uint16_t padding_width,

        const uint16_t out_depth,
        const uint16_t out_height,
        const uint16_t out_width,

        const uint32_t in_hw,
        const uint64_t in_dhw,
        const uint64_t in_cdhw,

        const uint32_t filter_hw,
        const uint64_t filter_dhw,
        const uint64_t filter_cdhw,

        const uint32_t out_hw,
        const uint64_t out_dhw,
        const uint64_t out_cdhw
){
    const uint8_t lane = __lane_id();

    const uint8_t n = lane & 31u;
    const uint8_t k = lane >> 5u;

    v16f vec_c = {.0f};

    uint32_t __row = ((blockIdx.x << 2) + (threadIdx.x >> 6)) * M_TILE;
    uint32_t __col = blockIdx.y * N_TILE;

    for (uint32_t i = 0; i < K; i += K_TILE){
        uint64_t slice_row = __row + n;

        uint64_t slice_col = i + k;

        uint32_t b = slice_row / out_dhw;
        uint32_t ic = slice_col / filter_dhw;
        int32_t id = slice_row / out_hw % out_depth + slice_col / filter_hw % filter_depth - padding_depth;
        int32_t ih = slice_row / out_width % out_height + slice_col / filter_width % filter_height - padding_height;
        int32_t iw = slice_row % out_width + slice_col % filter_width - padding_width;

        bool valid = (b < batch_size) && (ic < in_channels) &&
                       (id >= 0) && (id < in_depth) &&
                       (ih >= 0) && (ih < in_height) &&
                       (iw >= 0) && (iw < in_width);

        float vec_a = valid ? in_tensor[(((b * in_channels + ic) * in_depth + id) * in_height + ih) * in_width + iw] : 0.0f;
        float vec_b = filter_tensor[__col + n + (i + k) * N];

        vec_c = __builtin_amdgcn_mfma_f32_32x32x2f32(vec_a, vec_b, vec_c, 0, 0, 0);
    }

    #pragma unroll 16
    for(uint8_t s = 0; s < 16; ++s){
        // printf("%d, %d, %d, %f\n", n, k, s, vec_c[s]);
        storer[n + __col + ((s << 1) + (k << 2) - (s & 3) + __row) * N] = vec_c[s];
    }
}

```

The code generated correct results (the TF32 version had a larger relative error, approximately 0.0006, compared to the FP32 version which was below 1e-7); however, their execution speeds were very similar, which I found puzzling. I achieved similar results using methods provided by rocWMMA (10% faster) as I did with the built-in instructions.

**My Questions:**

1. **Benchmark Code:** Is there any official benchmark or sample code available to properly test TF32 performance on the MI300X?

2. **Configuration Settings:** Are there specific settings or configurations required to enable TF32 acceleration and achieve the advertised speedup?

3. **Best Practices:** What are the recommended practices for testing and validating TF32 performance on this GPU?

I would like to reproduce the 4x speedup as mentioned in the datasheet. Any guidance or references would be greatly appreciated.

Thank you!

**Comment by ppanchad-amd** [comment]
Hi @Moltres-Galar. Internal ticket has been created to assist with your issue. Thanks!

**Comment by cgmillette** [comment]
Hi @Moltres-Galar. Thanks for your message.

1. and 2. Benchmarking code: You can build the benchmarks from [source](https://github.com/ROCm/rocWMMA/blob/develop/README.md#build-with-cmake), using the option ROCWMMA_BUILD_BENCHMARK_TESTS=ON in cmake. We typically use the "gemm_***-bench" executables to capture performance information. These benchmarks will cover the entire gamut of parameters.

If you want to adjust the parameters for yourself, feel free to try out the [ad-hoc test](https://github.com/ROCm/rocWMMA/blob/develop/test/gemm/gemm_PGR1_LB2_MP0_MB_CP/test/ad_hoc_test.cpp).  You can edit and test out different parameters such as datatypes (tuple order for types is Input, Output, Compute) and problem sizes (M, N, K dimensions). The executable will be called gemm_PGR1_LB2_MP0_MB_CP_ad_hoc-bench.

Example:  
`using Types      = std::tuple<std::tuple<xfloat32_t, float32_t, float32_t>>;` for TF32
`using Types      = std::tuple<std::tuple<float32_t, float32_t, float32_t>>;` for F32

3. Please note there are many variables at play when it comes to benchmarking your kernels. When you record performance, it is a good idea to do so when the device has reached a kind of 'steady state' : meaning low std deviation between runs. When a GPU is 'cold' (high std dev), it needs to ramp to operating frequency and adjust to the temperature and the load. Once the GPU is 'hot' (low std dev), then it's a good idea to start taking samples and averaging over a time period. Therefore, you might sequentially run X 'cold runs' (samples not used) and Y 'hot runs' (samples are used). You could ensure the problem size of the kernel is big enough so that there is enough time to 'warm up' to the GPU, as well as reduce over-confident results due to cache hits from previous runs (or can cycle to a different memory pointer). 

In the ad-hoc example above, you can adjust the cold/hot runs [here](https://github.com/ROCm/rocWMMA/blob/develop/test/gemm/gemm_kernel_base_impl.hpp#L395). You can monitor your GPUs performance to guide hot / cold runs.
 
Other considerations (which are likely as important):
Peak throughputs often require many things to work together: optimal memory accesses, keeping matrix units busy, hiding latencies, etc. **Just because there may be an anticipation of 4x throughput of a particular instruction doesn't mean the entire kernel is going to have 4x speedup**. This is just one part of the entire equation and requires analysis of _how_ you implement the rest of the kernel too.

For example: 
* Strided memory accesses are slower than contiguous element accesses.
* The K-Tile for loop contains several integer divisions by function arguments which can be very expensive.
* There is a ternary conditional `float vec_a = valid ? in_tensor[...` in the loop, which in effect always forces a memory fetch.
* Inputs to the mfma instruction are memory fetches, which means it cannot execute until the memory fetches are completed.

Just by inspection, the performance impact of the mfma instruction could be less visible in this kernel because may be performance noise added by the points above. This is a sign that the kernel could use some optimization to bring more of the mfma impact to the surface.

Some suggestions:
* Try to pick an input memory layout that provides as much contiguous memory access as possible.
* Try to prefetch mfma inputs. This can help reduce impacts of data dependencies by hiding memory fetch latencies.
* For as many of the input arguments as possible: if they are known at compile-time, try using template parameters or constexpr helper functions to have the compiler pre-process logic as much as possible. It can help avoid expensive things such as run-time branching and integer division.
* Check out the generated assembly code [ROCWMMA_BUILD_ASSEMBLY=ON] (recommend only building ad-hoc test with this and not the entire test suite - it adds a lot of compile time). Inspect the generated code to see if it is efficient.

Hope this helps!

**Comment by Kyogre-Primal** [comment]
Thank you for your valuable feedback. As a beginner, I apologize for any improper issues and appreciate your understanding. I recognize that most of the performance bottlenecks stem from my memory access rather than the computation itself.

Regarding your suggestions:
	1.	I attempted to optimize the memory reads caused by ternary operators, but unfortunately, using if-else branches resulted in a 6% decrease in overall efficiency in multiple tests. I suspect this might be due to thread divergence?
	2.	I tried using wmma for my code; while the speed with xf32 didn’t meet my initial expectations, it performed well and the results were accurate. As for the issues with integer division and strided memory access, I find the sequence optimization overly complex, potentially degrading to explicit matrix multiplication considering the significant memory pressure. I currently don’t have a better solution.

I embarked on optimizing convolution primarily because the performance of the 300X convolution is weaker compared to Nvidia’s H100, which is about 260% faster. I initially speculated this was due to the latter’s use of tf32 data type. However, even with xf32, the performance hasn’t reached the expected levels, currently standing at about 240%.

I will continue to explore reasonable memory access structures for further optimization. Thank you for your assistance so far, and I wish you success in your endeavors.

**Comment by cgmillette** [comment]
Hi @Moltres-Galar. 
Yes- branching in code not great for hot-loops for lots of reasons - can reduce instruction cache hits, and it can reduce the ability of the compiler to optimize because of scoping. 
From what I can gather so far in your example, other low hanging fruits you can try are:
* If you can reduce any of the function args to constants known at compile time.
* Try to keep scalar and vector arithmetic separated as possible (e.g., scalar = values not dependent on threadIdx, which are the same for entire wavefront). Scalar and vector units can co-issue instructions.
* Try using floating point arithmetic for division. You can also try [fast floating point math](https://rocm.docs.amd.com/projects/HIP/en/docs-6.0.0/reference/math_api.html#fdividef) or other tricks such as multiply by reciprocal that are faster and less accurate, but may be sufficient for your needs (integer indexing).
* Definitely try a prefetch for your vec_a and vec_b data. Before the loop, fetch and buffer values of vec_a and vec_b. During the loop, fetch the NEXT vec_a and vec_b, while doing mfma with the buffered values. Then swap the new values into the buffer. This should allow you to hide some of the latencies of slower memory accesses with your mfma.

Thank you, I appreciate the well wishes, and I extend them to you as well! Your questions are appreciated, happy to help.
